language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kootiktok/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kootiktok/react-test npm run test -- --coverage

after_success:
  - docker build -t kootiktok/multi-client ./client
  - docker build -t kootiktok/multi-nginx ./nginx
  - docker build -t kootiktok/multi-server ./server
  - docker build -t kootiktok/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push kootiktok/multi-client
  - docker push kootiktok/multi-nginx
  - docker push kootiktok/multi-server
  - docker push kootiktok/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker-nginx'
  env: 'MultiDockerNginx-env'
  bucket_name: 'elasticbeanstalk-us-east-2-593361893208'
  bucket_path: 'docker-nginx'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
